services:
    web_dev:
        build: .
        command: poetry run python /code/manage.py runserver 0.0.0.0:8000
        restart: always
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.local