services:
    web_dev:
        build: .
        command:  bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
        restart: always
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.local